### ISSUE TITLE
Maintaining compiler compatibility

### ISSUE THREAD

**Issue by bee-rock** [bloomen/conwaygame#1]
Hi Christian,

I'm currently compiling with the g++ version that comes with Ubuntu 14.04: 

brock@brock-desktop:~/git/conwaygame$ g++ --version
g++ (Ubuntu 4.8.4-2ubuntu1~14.04.1) 4.8.4

However, I was unable to compile the tests again:

test_rules.cpp: In function ‘void test_n_alive_neighbors::make_test_one_alive(int, int)’:
test_rules.cpp:26:39: error: invalid operands of types ‘const char [2]’ and ‘int’ to binary ‘operator<<’
   ASSERT_EQUAL_MSG(1, n_alive, "(" << i << ", " << j << ")");

I can push a fix for this, but it amounts to creating a stringstream and then piping the message into it. Though this does increase the number of lines of code. I couldn't figure out the appropriate cast to do it without 2 lines.

Anyway, I have a feeling this is going to keep happening unless we consolidate our development environments.

**Comment by bloomen** [comment]
Hi Brock,

I don't think there is a need to use the same compiler. The code we write should be portable C++11. Just make it work on your compiler and I will later review the changes.

**Comment by bee-rock** [comment]
Do you want me to just push directly to master or branch/merge?

**Comment by bloomen** [comment]
Master directly is fine for now

**Comment by bloomen** [comment]
I just compiled with gcc4.8.5 myself and did not have any problems. make check works just fine prior to your code changes. It seems to me there is something weird going on with your compiler?
